name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: âš™ï¸ Terraform Deployment
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: â˜ï¸ Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: ğŸŒ± Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: ğŸ“ Change to terraform directory
        working-directory: terraform
        run: pwd

      - name: ğŸ” Terraform Init
        working-directory: terraform
        run: terraform init

      - name: ğŸ” Terraform Format Check
        working-directory: terraform
        run: terraform fmt -check

      - name: ğŸ§ª Terraform Plan
        working-directory: terraform
        run: terraform plan -out=tfplan

      - name: ğŸš€ Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve tfplan